name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Before you fill this form, please check whether your issue has already been reported previously in either the open or closed issues. If it is new, please submit as an issue. Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: module
    attributes:
      label: Scripts
      description: Which script you were running?
      multiple: true
      options:
        - 00-setup_folders.sh
        - 01-check_data.sh
        - 02a-snp_data.sh
        - 02b-convert_snp_format.sh
        - 03a-methylation_variables.sh
        - 03b-methylation_adjustment1.sh
        - 03c-methylation_pcs.sh
        - 03d-non_genetic_methylation_pcs.sh
        - 03e-methylation_adjustment2.sh
        - 03f-convert_methylation_format.sh
        - 03g-perform_positive_control.sh
        - 04a-convert_snp_format.sh
        - 04b-mapper-preparation.sh
        - 04c-create_mapper_files.sh
        - 04d-encoding.sh
        - 04e-single-site-analysis.sh
        - 04f-mqtl.sh
        - 06a-interaction_data_processing.sh
        - 06b-cell_interaction.sh
        - 07a-vmeQTL_data_preparation.sh
        - 07b-run_cis_vmeQTL.sh
        - 08a-genotypeInversion.sh
        - 08b-inversionmeQTL.sh
        - 08c-IWAS_phenotype.sh
        - 08d-mediation_inversion_CpG_phenotype.sh
        - 09-PRS_EWAS.sh
        - 10a-gwas_aar.sh
        - 10b-heritability_aar.sh
        - 11a-gwas_smoking.sh
        - 11b-heritability_smoking.sh
        - 11c-check_compress_data.sh
        - 14-nc886_gwas.sh
        - check_upload.sh
        - godmc_03b_aggregate.sh
        - godmc_03e_aggregate.sh
        - godmc_06a.sh
        - godmc_06b.sh
        - godmc_06b_run.sh
        - godmc_07a.sh3
        - godmc_07b_run.sh
        - godmc_07b_submit.sh
        - godmc_07c.sh
        - godmc_07c_run.sh
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What was the error message? Could you please provide as many details as possible when you run the scripts?
      placeholder: A bug happened when I run the [script]...
    validations:
      required: true
  - type: textarea
    id: Reproduce
    attributes:
      label: How can the bug be reproduced?
      description: Also tell us your system's specifications if possible
      placeholder: In order to repeat this bug you can...
    validations:
      required: false
  - type: dropdown
    id: Rversion
    attributes:
      label: "R version"
      description: What version of R are you running?
      multiple: false
      options:
        - 4.4.0 (April, 2024)
        - 4.3.3 (February, 2024)
        - 4.3.2 (October, 2023)
        - 4.3.1 (June, 2023)
        - 4.3.0 (April, 2023)
        - 4.2.3 (March, 2023)
        - 4.2.2 (October, 2022)
        - 4.2.1 (June, 2022)
        - 4.2.0 (April, 2022)
        - 4.1.3 (March, 2022)
        - 4.1.2 (November, 2021)
        - 4.1.1 (August, 2021)
        - 4.1.0 (May, 2021)
        - 4.0.5 (March, 2021)
        - 4.0.4 (February, 2021)
        - 4.0.3 (October, 2020)
        - 4.0.2 (June, 2020)
        - 4.0.1 (June, 2020)
        - 4.0.0 (April, 2020)
        - Older than 4.0.0
    validations:
      required: true
  - type: dropdown
    id: Python-Version
    attributes:
      label: "Python version"
      description: What version of Python are you running?
      multiple: false
      options:
        - 3.12
        - 3.11
        - 3.10
        - 3.9
        - 3.8
        - 3.7
        - 3.6
        - 3.5
        - 3.4
        - Older than 3.4
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output where you can find in the ${home_directory}/results/. This will be automatically formatted into code, so no need for backticks.
      render: shell
